### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by brd** [koitsu/bsdhwmon#1]
Hey Jeremy,

Do you plan on cutting a new release soon? I would like to use your JSON support.

Thanks!

**Comment by koitsu** [comment]
Brad, can you download a tarball of the current master on git, build it locally (should just be "make" and then you can test using the bsdhwmon binary that gets built) and make sure it works as you'd hope?  I haven't done much testing of the JSON output mode, but it ideally should work.

The tarball is always available via https://github.com/koitsu/bsdhwmon/archive/master.tar.gz

**Comment by brd** [comment]
Hi Jeremy,

I installed the pkg from The FreeBSD Ports Collection initially. When I noticed the JSON support was not available there, I forked the github project. I will test and let you know if I find any bugs in the JSON support. Then maybe if it works ok, could you cut a new release?

Would you be interested in the script I am writing to take data from bsdhwmon and put it into a graphing system called Graphite? Maybe it could go in a contrib folder or something.

Thanks,
Brad Davis

**Comment by koitsu** [comment]
I'm not sure why you needed to fork the release when you could have just downloaded the tarball for testing.  :-)  Seems overkill.  If it works, that's good feedback for me.  I'll try to get a new release out as soon as that's done, but it may take me a week plus the time it takes the FreeBSD Ports folks to get around to the bug/PR I have to file.

As for the graphing: no, I'd have no interest in that.  I have to deal with Graphite as part of my day job and I find it to be atrocious in numerous regards; if you want to maintain something publicly that offers that up, that'd be great, but I wouldn't benefit from it.  I have my own graphing stuff that I've written using a simple perl script, Dygraphs (which is interactive and client-side), and a very simple HTML file.  Example: https://www.dropbox.com/s/ljvuxdm6u8y4l1c/bsdhwmon.png?dl=0

**Comment by brd** [comment]
I can commit the update to ports when the time comes.

Yeah, I am not a big fan of graphite, but it has proven useful in some respects, i.e. easy to display custom time periods. It would be nice if you could put it in a contrib folder maybe with a big unsupported warning. Just to provide it as an option for others.

**Comment by grembo** [comment]
Just committed https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199793, so 20150429 is in ports now and will be available using pkg in a few days from now.

**Comment by koitsu** [comment]
Closing; bsdhwmon-20150429 is available in ports and on package servers.

If you find issues with the JSON output mode, please file a new Issue here on github and I'll take care of it ASAP.  Thanks!
